apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: {{ .Values.global.name }}-bridge
spec:
  replicas: {{ .Values.kafka.bridgeReplicas }}
  bootstrapServers: {{ .Values.global.name }}-cluster-kafka-bootstrap:9092
  http:
    port: 8080
