apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ .Values.global.name }}-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.8.0
  replicas: 1
  bootstrapServers: {{ .Values.global.name }}-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: {{ .Values.global.name }}-cluster-cluster-ca-cert
        pattern: "*.crt"
  image: viniro/ddp-os-kafka-kafka-connect:v0.0.1
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1