apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-helm-values
data:
  KAFKA_CLUSTERS_0_NAME: "{{ .Values.global.name }}-cluster"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "{{ .Values.global.name }}-cluster-kafka-bootstrap:9092"
  AUTH_TYPE: "DISABLED"
  MANAGEMENT_HEALTH_LDAP_ENABLED: "FALSE" 